Congreso-1/Controllers/CongressesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Congreso_1.Models;
using Microsoft.Ajax.Utilities;
using Microsoft.AspNet.Identity;

namespace Congreso_1.Controllers
{
    public class CongressesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        private ApplicationUser Usuario = new ApplicationUser();
        // GET: Congresses
        //Controlador para el acceso de usuario y adminitrador a la vista Index de los congresos obtiene el rol registrado y le carga los datos dependiendo el Rol, en la vista maneja la misma logica de mostrar datos por rol
        public ActionResult Index()
        {
            ViewBag.Rol = ObtenerRol().ToString();
            var consulta = new List<Congress>();
            if (ViewBag.Rol == "Usuario")
            {
                var usuarioID = User.Identity.GetUserId();
                Usuario = db.Users.Where(x => x.Id == usuarioID).FirstOrDefault();
                consulta = (from congreso in db.Tb_Congress
                                join CongresoEmpresa in db.Tb_Congress_Enterprise on congreso.CongressId equals CongresoEmpresa.CongressId
                                join empresa in db.Tb_Enterprise on CongresoEmpresa.EnterpriseId equals empresa.EnterpriseId
                                where empresa.EnterpriseId == Usuario.EnterpriseId
                                select congreso).ToList();
                consulta = consulta.DistinctBy(x => x.CongressId).ToList();
            }
            else if(ViewBag.Rol == "Admin")
            {
                consulta = (from congreso in db.Tb_Congress
                            select congreso).ToList();
                consulta = consulta.DistinctBy(x => x.CongressId).ToList();

            }
            return View(consulta);

        }

        // GET: Congresses/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Congress congress = db.Tb_Congress.Find(id);
            if (congress == null)
            {
                return HttpNotFound();
            }
            return View(congress);
        }

        // GET: Congresses/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Congresses/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(HttpPostedFileBase CongressBanner, [Bind(Include = "CongressId,CongressName,CongressTheme,CongressInitialDate,CongressFinalDate,Available")] Congress congress)
        {
            if (ModelState.IsValid)
            {
                if (CongressBanner != null)
                {
                    var fecha = DateTime.Now.ToString().Replace(" ", "-");
                    String ruta = Server.MapPath("~/Archivos/Subidos/");
                    var rutaLink = ("../../Archivos/Subidos/" + (DateTime.Now.ToString("yyyyMMddHHmmss") + "-" + CongressBanner.FileName).ToLower());
                    ruta += (DateTime.Now.ToString("yyyyMMddHHmmss") + "-" + CongressBanner.FileName).ToLower();
                    CongressBanner.SaveAs(ruta);
                    congress.CongressBanner = rutaLink;
                }

                db.Tb_Congress.Add(congress);
                db.SaveChanges();

                return RedirectToAction("Index");
            }
           

            return View(congress);
        }

        // GET: Congresses/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Congress congress = db.Tb_Congress.Find(id);
            if (congress == null)
            {
                return HttpNotFound();
            }
            return View(congress);
        }

        // POST: Congresses/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CongressId,CongressName,CongressTheme,CongressInitialDate,CongressFinalDate,Available")] Congress congress)
        {
            if (ModelState.IsValid)
            {
                db.Entry(congress).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(congress);
        }

        // GET: Congresses/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Congress congress = db.Tb_Congress.Find(id);
            if (congress == null)
            {
                return HttpNotFound();
            }
            return View(congress);
        }

        // POST: Congresses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Congress congress = db.Tb_Congress.Find(id);
            db.Tb_Congress.Remove(congress);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        public string ObtenerRol()
        {
            string userId = User.Identity.GetUserId();
            ApplicationDbContext db = new ApplicationDbContext();
            string rol = db.Users.Where(x => x.Id == userId).FirstOrDefault().Rol.ToString();
            return rol;
        }

    }
}

Congreso-1/Views/Congresses/Create.cshtml
@model Congreso_1.Models.Congress

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "Congresses", FormMethod.Post, new { enctype = "multipart/form-data" })) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Congress</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.CongressName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.CongressName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.CongressName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.CongressTheme, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.CongressTheme, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.CongressTheme, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.CongressInitialDate, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.CongressInitialDate, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.CongressInitialDate, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.CongressFinalDate, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.CongressFinalDate, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.CongressFinalDate, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Available, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Available, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Available, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.CongressBanner, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="file" name="CongressBanner" id="CongressBanner">
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Congreso-1/Views/Congresses/Delete.cshtml
@model Congreso_1.Models.Congress

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Congress</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CongressName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CongressName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CongressTheme)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CongressTheme)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CongressInitialDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CongressInitialDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CongressFinalDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CongressFinalDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Available)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Available)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Congreso-1/Views/Congresses/Details.cshtml
@model Congreso_1.Models.Congress

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Congress</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CongressName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CongressName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CongressTheme)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CongressTheme)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CongressInitialDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CongressInitialDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CongressFinalDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CongressFinalDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Available)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Available)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.CongressId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Congreso-1/Views/Congresses/Edit.cshtml
@model Congreso_1.Models.Congress

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Congress</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.CongressId)

        <div class="form-group">
            @Html.LabelFor(model => model.CongressName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CongressName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CongressName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CongressTheme, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CongressTheme, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CongressTheme, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CongressInitialDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CongressInitialDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CongressInitialDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CongressFinalDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CongressFinalDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CongressFinalDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Available, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Available, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Available, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Congreso-1/Views/Congresses/Index.cshtml
@model IEnumerable<Congreso_1.Models.Congress>

@{
    ViewBag.Title = "Index";
}
@if (ViewBag.Rol == "Usuario")
{
<table class="table">
    @foreach (var item in Model)
    {
        <div style="background:#eaeaea" class="row">

            <div class="col-md-6" style="border-right: 2px solid @item.CongressColorA;">
                <center><img src="@item.CongressBanner" style="width: 450px; padding: 10px;" /></center>
            </div>
            <div class="col-md-6" style="padding:10px">
                <h2 style="color:@item.CongressColorA">
                    @Html.DisplayFor(modelItem => item.CongressName)
                </h2>
                <br />
                <p>
                    @Html.DisplayFor(modelItem => item.CongressTheme)
                </p>
                <br />
                <p>
                    @Html.DisplayFor(modelItem => item.CongressInitialDate) -   @Html.DisplayFor(modelItem => item.CongressFinalDate)
                </p>
                <br />

                @*@Html.ActionLink("Edit", "Edit", new { id=item.CongressId }) |
                    @Html.ActionLink("Details", "Details", new { id=item.CongressId }) |
                    @Html.ActionLink("Delete", "Delete", new { id=item.CongressId })*@
                @Html.ActionLink("Ingresar", "Index", "Home", new { IdCongreso = item.CongressId }, new { @style = "background:" + item.CongressColorA + ";color:#ffffff; width: 200px;", @class = "btn btn - warning" })
            </div>
        </div>
    }

</table>


}
else if (ViewBag.Rol == "Admin")
{

<h2>Index2</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.CongressName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CongressTheme)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CongressInitialDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CongressFinalDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Available)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.CongressName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CongressTheme)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CongressInitialDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CongressFinalDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Available)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.CongressId }) |
                @Html.ActionLink("Details", "Details", new { id = item.CongressId }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.CongressId }) |
                @Html.ActionLink("Ir Stands", "Index", "Stands", new { idCongreso = item.CongressId }, null) |

            </td>
        </tr>
    }

</table>
}

Congreso-1/Views/Congresses/Index2.cshtml
@model IEnumerable<Congreso_1.Models.Congress>

@{
    ViewBag.Title = "Index2";
}

<h2>Index2</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.CongressName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CongressBanner)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CongressTheme)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CongressColorA)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CongressColorB)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CongressInitialDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CongressFinalDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Available)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.CongressName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CongressBanner)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CongressTheme)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CongressColorA)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CongressColorB)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CongressInitialDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CongressFinalDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Available)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.CongressId }) |
            @Html.ActionLink("Details", "Details", new { id=item.CongressId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.CongressId })
        </td>
    </tr>
}

</table>